routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();


Route::get('/bahan-kajian/grid', 'BahanKajianController@grid');
Route::resource('/bahan-kajian', 'BahanKajianController');
Route::get('/blooms-taxonomy/grid', 'BloomsTaxonomyController@grid');
Route::resource('/blooms-taxonomy', 'BloomsTaxonomyController');
Route::get('/cpl/grid', 'CplController@grid');
Route::resource('/cpl', 'CplController');
Route::get('/mata-kuliah/grid', 'MataKuliahController@grid');
Route::resource('/mata-kuliah', 'MataKuliahController');
Route::get('/okupasi/grid', 'OkupasiController@grid');
Route::resource('/okupasi', 'OkupasiController');
Route::get('/permission-role/grid', 'PermissionRoleController@grid');
Route::resource('/permission-role', 'PermissionRoleController');
Route::get('/permission/grid', 'PermissionController@grid');
Route::resource('/permission', 'PermissionController');
Route::get('/prodi/grid', 'ProdiController@grid');
Route::resource('/prodi', 'ProdiController');
Route::get('/profil-lulusan/grid', 'ProfilLulusanController@grid');
Route::resource('/profil-lulusan', 'ProfilLulusanController');
Route::get('/ranah-topik/grid', 'RanahTopikController@grid');
Route::resource('/ranah-topik', 'RanahTopikController');
Route::get('/rel-cpl-bk/grid', 'RelCplBkController@grid');
Route::resource('/rel-cpl-bk', 'RelCplBkController');
Route::get('/rel-topik-bk/grid', 'RelTopikBkController@grid');
Route::resource('/rel-topik-bk', 'RelTopikBkController');
Route::get('/rel-topik-mk/grid', 'RelTopikMkController@grid');
Route::resource('/rel-topik-mk', 'RelTopikMkController');
Route::get('/role/grid', 'RoleController@grid');
Route::resource('/role', 'RoleController');
Route::get('/user-prodi/grid', 'UserProdiController@grid');
Route::resource('/user-prodi', 'UserProdiController');
Route::get('/user-role/grid', 'RoleUserController@grid');
Route::resource('/user-role', 'RoleUserController');
Route::get('/users/grid', 'UserController@grid');
Route::resource('/users', 'UserController');

app/Okupasi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Okupasi extends Model
{
    //
    protected $table = 'okupasi';
    public $timestamps = false;

    public function profil(){
    	return $this->belongsTo(ProfilLulusan::class,'profil_lulusan_id');
    }
}

app/Http/Controllers/OkupasiController.php
<?php


namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\Controller;

use App\Okupasi;
use App\ProfilLulusan;
use Lang;

class OkupasiController extends Controller
{
	//
	public function __construct()
	{
		//$this->middleware('auth');
	}


	public function index(Request $request)
	{
		return view('okupasi.index');
	}

	public function create(Request $request)
	{
		$profil = ProfilLulusan::select('id','nama')->get();
		return view('okupasi.add', ['model' => new Okupasi(),'profil'=>$profil]);
	}

	public function edit(Okupasi $okupasi)
	{
		$profil = ProfilLulusan::select('id','nama')->get();
		return view('okupasi.add', ['model' => $okupasi,'profil'=>$profil]);
	}

	public function show(Okupasi $okupasi)
	{
		return view('okupasi.show', ['model' => $okupasi]);
	}

	public function grid(Request $request)
	{
		$length = $request->get('length');
		$start  = $request->get('start');
		$orders = $request->get('order');
		$search = $request->get('search');
		$columns = ['okupasi.id','okupasi.nama','okupasi.deskripsi','profil_lulusan.nama as profil'];
		$columnsSearch = ['okupasi.id','okupasi.nama','okupasi.deskripsi','profil_lulusan.nama'];

		$query   = Okupasi::select($columns)->join('profil_lulusan','okupasi.profil_lulusan_id','=','profil_lulusan.id');

		if($search['value']){
			$query->where(function($query) use ($search, $columnsSearch){
				foreach($columnsSearch as $column){
					$query->orWhere($column, 'like', '%'.$search['value'].'%');
				}
			});
		}

		foreach($orders as $order){
			$query->orderBy($columnsSearch[$order['column']], $order['dir']);
		}

		$result = new \stdClass();
		$result->iTotalDisplayRecords = $query->count();
		$result->data  = $query->take($length)->skip($start)->get();

		foreach($result->data as &$item){
			$html = array();

			$html[] = '<div class="mini ui buttons">';

			$html[] = '<a href="'.route('okupasi.show', $item->id).'" class="ui blue button">';
			$html[] = '<i class="file alternate icon" style="margin:0px"></i>';
			$html[] = '</a>';

			$html[] = '<a href="'.route('okupasi.edit', $item->id).'" class="ui yellow button">';
			$html[] = '<i class="edit icon" style="margin:0px"></i>';
			$html[] = '</a>';

			$html[] = '<a href="#" onclick="return doDelete('.$item->id.')" class="ui red button">';
			$html[] = '<i class="trash alternate icon" style="margin:0px"></i>';
			$html[] = '</a>';

			$html[] = '</div>';

			$item->buttons = implode('', $html);
		}

		echo json_encode($result);
	}

	private function validateForm(Request $request){
		$id     = $request->input('id');
		$unique = $id? 'okupasi,nama,'.$id : 'okupasi,nama';

		$this->validate($request, [
			'nama' => 'required|unique:'.$unique,
			'deskripsi' => 'required',
			'profil_lulusan_id' => 'required',
		]);
	}

	private function setAttributes(Okupasi $item, Request $request){
		$item->nama = $request->nama;
		$item->deskripsi = $request->deskripsi;
		$item->profil_lulusan_id = $request->profil_lulusan_id;
	}


	public function update(Request $request) {
		$this->validateForm($request);

		$item = Okupasi::findOrFail($request->input('id'));
		$this->setAttributes($item, $request);

		$status = $item->save();
		if($status)
			return redirect()->route('okupasi.index')->with('status', $status)->with('messages', Lang::get('app.save_success'));
		else
			return redirect()->route('okupasi.edit', $item->id);

	}

	public function store(Request $request)
	{
		$this->validateForm($request);

		$item = new Okupasi();
		$this->setAttributes($item, $request);

		$status = $item->save();
		if($status)
			return redirect()->route('okupasi.index')->with('status', $status)->with('messages', Lang::get('app.save_success'));
		else
			return redirect()->route('okupasi.edit', $item->id);
	}

	public function destroy(Okupasi $okupasi) {
		$okupasi->delete();
		
		return "OK";
	}


}

resources/views/okupasi/add.blade.php
@extends('layouts.master')

@section('content')
<div class="ui card fluid">
	<div class="content">
		<div class="ui breadcrumb">
			<div class="section">{{ Lang::get('app.home') }}</div>
			<i class="right angle icon divider"></i>
			<a href="{{ route('okupasi.index') }}" class="section">{{ Lang::get('app.okupasi') }}</a>
			<i class="right angle icon divider"></i>
			@if(!empty($model->id))
			<div class="section">{{ $model->nama }}</div>
			<i class="right angle icon divider"></i>
			@endif
			<div class="active section">
				@if(!empty($model->id)) {{ Lang::get('app.edit') }} @else {{ Lang::get('app.add') }} @endif
				{{ Lang::get('app.okupasi') }}
			</div>
		</div>
	</div>
</div>
<div class="ui card fluid">
	<div class="content">
		<div class="description">
			@php $action = empty($model->id)? route('okupasi.store') : route('okupasi.update', $model->id); @endphp
			<form action="{{ $action }}" method="POST" class="ui form @if($errors) error @endif">
				{{ csrf_field() }}

				@if(!empty($model->id))
				<input type="hidden" name="_method" value="PUT">
				@endif

				<input type="hidden" name="id" id="id" value="{{ $model->id }}" readonly="readonly">
				<div class="field">
					<label>{{ Lang::get('app.nama') }}</label>
					<input type="text" name="nama" id="nama" value="{{ old('nama', $model->nama) }}">
				</div>
				{!! $errors->has('nama')?'<div class="ui error message"> <p> '.$errors->first('nama').'</p> </div>':'' !!}
				<div class="field">
					<label>{{ Lang::get('app.deskripsi') }}</label>
					<input type="text" name="deskripsi" id="deskripsi" value="{{ old('deskripsi', $model->deskripsi) }}">
				</div>
				{!! $errors->has('deskripsi')?'<div class="ui error message"> <p> '.$errors->first('deskripsi').'</p> </div>':'' !!}
				<div class="field">
					<label>{{ Lang::get('app.profil_lulusan') }}</label>
					<select class="ui search dropdown" name="profil_lulusan_id" id="profil_lulusan_id">
						<option value="">{{ Lang::get('app.profil_lulusan') }}</option>
						@foreach($profil as $val)
						<option value="{{ $val->id }}" {{ $model->profil_lulusan_id == $val->id? 'selected' : '' }}>
							{{ $val->nama }}
						</option>
						@endforeach
					</select>
				</div>
				{!! $errors->has('profil_lulusan_id')?'<div class="ui error message"> <p> '.$errors->first('profil_lulusan_id').'</p> </div>':'' !!}

				<div class="ui small buttons">
					<button type="submit" class="ui green button">
						<i class="check square icon"></i> {{ Lang::get('app.save') }}
					</button>
					<a class="ui yellow button" href="{{ route('okupasi.index') }}">
						<i class="hand point left outline icon"></i> {{ Lang::get('app.cancel') }}
					</a>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/okupasi/index.blade.php
@extends('layouts.master')

@section('content')
<div class="ui card fluid">
	<div class="content">
		<div class="ui breadcrumb">
			<div class="section">{{ Lang::get('app.home') }}</div>
			<i class="right angle icon divider"></i>
			<div class="active section">{{ Lang::get('app.okupasi') }}</div>
		</div>
	</div>
</div>
<div class="ui card fluid">
	<div class="extra content">
		<div class="ui grid">
			<div class="three wide column">
				<a href="{{ route('okupasi.create')}}" class="ui small green button">
					<i class="plus square icon"></i> {{ Lang::get('app.add') }}
				</a>
			</div>
			<div class="thirteen wide column">
				<!-- Messages -->
				@php $messages = session('messages'); @endphp
				@if($messages)
				@if(is_array($messages))
				<div class="ui small @if(session('status') == 1) positive @else negative @endif message" role="alert">
					<ul>
						@foreach($messages as $message)
						<li>{{ $message }}</li>
						@endforeach
					</ul>
				</div>
				@else
				<div class="ui small @if(session('status') == 1) positive @else negative @endif message" role="alert">
					{{ session('messages') }}
				</div>
				@endif
				@endif
			</div>
		</div>
	</div>
	<div class="content">
		<div class="description">
			<table class="ui celled red table responsive" cellspacing="0" width="100%" id="thegrid">
				<thead>
					<tr>
						<th>{{ Lang::get('app.id') }}</th>
						<th>{{ Lang::get('app.nama') }}</th>
						<th>{{ Lang::get('app.deskripsi') }}</th>
						<th>{{ Lang::get('app.profil_lulusan') }}</th>
						<th style="width:50px"></th>
					</tr>
				</thead>
				<tbody></tbody>
			</table>
		</div>
	</div>
</div>
@endsection
@section('scripts')
<script type="text/javascript">
	var theGrid = null;
	$(document).ready(function(){
		theGrid = $('#thegrid').DataTable({
			'info'      : false,
			'drawCallback': function (settings) { 
				$(".dataTables_filter").each(function () { 
					$(this).find("label").addClass('ui input field'); 
				}); 
			},
			'ordering'  : true,
			'processing': true,
			'responsive': true,
			'serverSide': true,
			'ajax'      : {
				url: "{{ route('okupasi.index')}}/grid",
				dataSrc: function(result){
					console.log(result);
					return result.data;
				}
			},
			columns: [
			{ data: 'id', name: 'id', searchable: false , width: '20px'},
			{ data: 'nama', name: 'nama' },
			{ data: 'deskripsi', name: 'deskripsi' },
			{ data: 'profil', name: 'profil' },
			{ data: 'buttons', name: 'buttons', orderable: false, searchable: false },
			],
			'language'  : {
				'emptyTable'    : Lang.datatable.no_data,
				'infoEmpty'     : Lang.datatable.no_data,
				'zeroRecords'   : Lang.datatable.no_data,
				'thousands'     : ',',
				'lengthMenu'    : Lang.datatable.showing_n_data,
				'loadingRecords': Lang.datatable.loading_data,
				'processing'    : Lang.datatable.processing_data,
				'search'        : "",
				'searchPlaceholder' : Lang.app.search,
				'paginate': {
					'first'     : '<<',
					'last'      : '>>',
					'next'      : '>',
					'previous'  : '<'
				}
			}
		});
	});

	function doDelete(id) {
		if(confirm('Apakah anda yakin ingin menghapus data ini?')) {
			$.ajax({ url: '{{ route('okupasi.index') }}/' + id, type: 'DELETE'}).done(function() {
				theGrid.ajax.reload();
			});
		}
		return false;
	}
</script>
@endsection

resources/views/okupasi/show.blade.php
@extends('layouts.master')

@section('content')
<div class="ui card fluid">
	<div class="content">
		<div class="ui breadcrumb">
			<div class="section">{{ Lang::get('app.home') }}</div>
			<i class="right angle icon divider"></i>
			<a href="{{ route('okupasi.index') }}" class="section">{{ Lang::get('app.okupasi') }}</a>
			<i class="right angle icon divider"></i>
			<div class="section">{{$model->nama}}</div>
			<i class="right angle icon divider"></i>
			<div class="active section">{{ Lang::get('app.detail') }}</div>
		</div>
	</div>
</div>
<div class="ui card fluid">
	<div class="content">
		<div class="description">
			<table class="ui celled table">
				<tbody>
					<tr>
						<td class="collapsing active">{{ Lang::get('app.id') }}</td>
						<td>{{ $model->id }}</td>
					</tr>
					<tr>
						<td class="collapsing active">{{ Lang::get('app.nama') }}</td>
						<td>{{ $model->nama }}</td>
					</tr>
					<tr>
						<td class="collapsing active">{{ Lang::get('app.deskripsi') }}</td>
						<td>{{ $model->deskripsi }}</td>
					</tr>
					<tr>
						<td class="collapsing active">{{ Lang::get('app.profil_lulusan') }}</td>
						<td>{{ $model->profil->nama }}</td>
					</tr>
				</tbody>
			</table>
			<!-- Buttons -->
			<div class="ui small buttons">
				<a class="ui yellow button" href="{{ route('okupasi.edit', $model->id) }}">
					<i class="edit icon"></i> {{ Lang::get('app.edit') }}
				</a>
				<a class="ui button" href="{{ route('okupasi.index') }}">
					<i class="hand point left outline icon"></i> {{ Lang::get('app.back') }}
				</a>
			</div>
		</div>
	</div>
</div>
@endsection