routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();


Route::get('/bahan-kajian/grid', 'BahanKajianController@grid');
Route::resource('/bahan-kajian', 'BahanKajianController');
Route::get('/blooms-taxonomy/grid', 'BloomsTaxonomyController@grid');
Route::resource('/blooms-taxonomy', 'BloomsTaxonomyController');
Route::get('/cpl/grid', 'CplController@grid');
Route::resource('/cpl', 'CplController');
Route::get('/mata-kuliah/grid', 'MataKuliahController@grid');
Route::resource('/mata-kuliah', 'MataKuliahController');
Route::get('/okupasi/grid', 'OkupasiController@grid');
Route::resource('/okupasi', 'OkupasiController');
Route::get('/permission-role/grid', 'PermissionRoleController@grid');
Route::resource('/permission-role', 'PermissionRoleController');
Route::get('/permission/grid', 'PermissionController@grid');
Route::resource('/permission', 'PermissionController');
Route::get('/prodi/grid', 'ProdiController@grid');
Route::resource('/prodi', 'ProdiController');
Route::get('/profil-lulusan/grid', 'ProfilLulusanController@grid');
Route::resource('/profil-lulusan', 'ProfilLulusanController');
Route::get('/ranah-topik/grid', 'RanahTopikController@grid');
Route::resource('/ranah-topik', 'RanahTopikController');
Route::get('/rel-cpl-bk/grid', 'RelCplBkController@grid');
Route::resource('/rel-cpl-bk', 'RelCplBkController');
Route::get('/rel-topik-bk/grid', 'RelTopikBkController@grid');
Route::resource('/rel-topik-bk', 'RelTopikBkController');
Route::get('/rel-topik-mk/grid', 'RelTopikMkController@grid');
Route::resource('/rel-topik-mk', 'RelTopikMkController');
Route::get('/role/grid', 'RoleController@grid');
Route::resource('/role', 'RoleController');
Route::get('/user-prodi/grid', 'UserProdiController@grid');
Route::resource('/user-prodi', 'UserProdiController');
Route::get('/user-role/grid', 'RoleUserController@grid');
Route::resource('/user-role', 'RoleUserController');
Route::get('/users/grid', 'UserController@grid');
Route::resource('/users', 'UserController');

app/RelTopikMk.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class RelTopikMk extends Model
{
    //
    protected $table = 'rel_topik_mk';
    public $timestamps = false;

 	public function mk(){
    	return $this->belongsTo(MataKuliah::class,'mk_id');
    }

    public function topik(){
    	return $this->belongsTo(RanahTopik::class,'topik_id');
    }
}

app/Http/Controllers/RelTopikMkController.php
<?php


namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\Controller;

use App\RelTopikMk;
use App\MataKuliah;
use App\RanahTopik;

use Lang;

class RelTopikMkController extends Controller
{
	//
	public function __construct()
	{
		//$this->middleware('auth');
	}


	public function index(Request $request)
	{
		return view('rel-topik-mk.index');
	}

	public function create(Request $request)
	{
		$kuliah = MataKuliah::select('id','nama')->get();
		$topik = RanahTopik::select('id','nama')->get();
		return view('rel-topik-mk.add', ['model' => new RelTopikMk(),'topik'=>$topik,'kuliah'=>$kuliah]);
	}

	public function edit(RelTopikMk $rel_topik_mk)
	{
		$kuliah = MataKuliah::select('id','nama')->get();
		$topik = RanahTopik::select('id','nama')->get();
		$rel = RelTopikMk::where('topik_id','=',$rel_topik_mk->topik_id)->get();
		return view('rel-topik-mk.add', ['model' => $rel_topik_mk,'topik'=>$topik,'kuliah'=>$kuliah,'rel'=>$rel]);
	}

	public function show(RelTopikMk $rel_topik_mk)
	{
		return view('rel-topik-mk.show', ['model' => $rel_topik_mk]);
	}

	public function grid(Request $request)
	{
		$length = $request->get('length');
		$start  = $request->get('start');
		$orders = $request->get('order');
		$search = $request->get('search');
		$columns = ['rel_topik_mk.id','ranah_topik.nama','mata_kuliah.nama as kuliah'];
		$columnsSearch = ['rel_topik_mk.id','ranah_topik.nama','mata_kuliah.nama'];

		$query   = RelTopikMk::select($columns)->join('ranah_topik','ranah_topik.id','=','rel_topik_mk.topik_id')->join('mata_kuliah','mata_kuliah.id','=','rel_topik_mk.mk_id');

		if($search['value']){
			$query->where(function($query) use ($search, $columnsSearch){
				foreach($columnsSearch as $column){
					$query->orWhere($column, 'like', '%'.$search['value'].'%');
				}
			});
		}

		foreach($orders as $order){
			$query->orderBy($columnsSearch[$order['column']], $order['dir']);
		}

		$result = new \stdClass();
		$result->iTotalDisplayRecords = $query->count();
		$result->data  = $query->take($length)->skip($start)->get();

		foreach($result->data as &$item){
			$html = array();

			$html[] = '<div class="mini ui buttons">';

			$html[] = '<a href="'.route('rel-topik-mk.show', $item->id).'" class="ui blue button">';
			$html[] = '<i class="file alternate icon" style="margin:0px"></i>';
			$html[] = '</a>';

			$html[] = '<a href="'.route('rel-topik-mk.edit', $item->id).'" class="ui yellow button">';
			$html[] = '<i class="edit icon" style="margin:0px"></i>';
			$html[] = '</a>';

			$html[] = '<a href="#" onclick="return doDelete('.$item->id.')" class="ui red button">';
			$html[] = '<i class="trash alternate icon" style="margin:0px"></i>';
			$html[] = '</a>';

			$html[] = '</div>';

			$item->buttons = implode('', $html);
		}

		echo json_encode($result);
	}

	private function validateForm(Request $request){
		$this->validate($request, [
			'topik_id' => 'required',
			'mk_id' => 'required',
		]);
	}

	private function setAttributes(RelTopikMk $item, $request){	
		$item->topik_id = $request->topik_id;
		$item->mk_id = $request->mk_id;
	}


	public function update(Request $request) {
		$this->validateForm($request);

		$del = RelTopikMk::where('topik_id','=',$request->topik_id)->get();
		foreach ($del as $key) {
			$key->delete();
		}
		foreach ($request->mk_id as $value) {
			$item = new RelTopikMk();
			$r = (object) ['topik_id'=>$request->topik_id,'mk_id'=>$value];
			$this->setAttributes($item, $r);
			$status = $item->save();
		}
		if($status)
			return redirect()->route('rel-topik-mk.index')->with('status', $status)->with('messages', Lang::get('app.save_success'));
		else
			return redirect()->route('rel-topik-mk.edit', $item->id);

	}

	public function store(Request $request)
	{
		$this->validateForm($request);

		$status = null;
		foreach ($request->mk_id as $value) {
			$item = new RelTopikMk();
			$r = (object) ['topik_id'=>$request->topik_id,'mk_id'=>$value];
			$this->setAttributes($item, $r);
			$status = $item->save();
		}

		if($status)
			return redirect()->route('rel-topik-mk.index')->with('status', $status)->with('messages', Lang::get('app.save_success'));
		else
			return redirect()->route('rel-topik-mk.edit', $item->id);
	}

	public function destroy(RelTopikMk $rel_topik_mk) {
		$rel_topik_mk->delete();
		
		return "OK";
	}


}

resources/views/rel-topik-mk/add.blade.php
@extends('layouts.master')

@section('content')
<div class="ui card fluid">
	<div class="content">
		<div class="ui breadcrumb">
			<div class="section">{{ Lang::get('app.home') }}</div>
			<i class="right angle icon divider"></i>
			<a href="{{ route('rel-topik-mk.index') }}" class="section">{{ Lang::get('app.rel_topik_mk') }}</a>
			<i class="right angle icon divider"></i>
			@if(!empty($model->id))
			<div class="section">{{ $model->topik->nama }}</div>
			<i class="right angle icon divider"></i>
			@endif
			<div class="active section">
				@if(!empty($model->id)) {{ Lang::get('app.edit') }} @else {{ Lang::get('app.add') }} @endif
				{{ Lang::get('app.rel_topik_mk') }}
			</div>
		</div>
	</div>
</div>
<div class="ui card fluid">
	<div class="content">
		<div class="description">
			@php $action = empty($model->id)? route('rel-topik-mk.store') : route('rel-topik-mk.update', $model->id); @endphp
			<form action="{{ $action }}" method="POST" class="ui form @if($errors) error @endif">
				{{ csrf_field() }}

				@if(!empty($model->id))
				<input type="hidden" name="_method" value="PUT">
				@endif

				<input type="hidden" name="id" id="id" value="{{ $model->id }}" readonly="readonly">
				<div class="field">
					<label>{{ Lang::get('app.topik') }}</label>
					<select class="ui search dropdown" name="topik_id" id="topik_id">
						<option value="">{{ Lang::get('app.topik') }}</option>
						@foreach($topik as $val)
						<option value="{{ $val->id }}" {{ $model->topik_id == $val->id? 'selected' : '' }}>
							{{ $val->nama }}
						</option>
						@endforeach
					</select>
				</div>
				{!! $errors->has('topik_id')?'<div class="ui error message"> <p> '.$errors->first('topik_id').'</p> </div>':'' !!}
				<div class="field">
					<label>{{ Lang::get('app.mata_kuliah') }}</label>
					<select class="ui search dropdown" name="mk_id[]" id="mk_id" multiple="multiple">
						<option value="">{{ Lang::get('app.mata_kuliah') }}</option>
						@foreach($kuliah as $val)
						@if(!empty($model->id))
						<option value="{{ $val->id }}"  @foreach($rel as $myval) {{ (($myval->mk_id==$val->id)?'selected':'') }} @endforeach >
							{{ $val->nama }}
						</option>
						@else
						<option value="{{ $val->id }}" {{ $model->mk_id == $val->id? 'selected' : '' }}>
							{{ $val->nama }}
						</option>
						@endif
						@endforeach
					</select>
				</div>
				{!! $errors->has('mk_id')?'<div class="ui error message"> <p> '.$errors->first('mk_id').'</p> </div>':'' !!}

				<div class="ui small buttons">
					<button type="submit" class="ui green button">
						<i class="check square icon"></i> {{ Lang::get('app.save') }}
					</button>
					<a class="ui yellow button" href="{{ route('rel-topik-mk.index') }}">
						<i class="hand point left outline icon"></i> {{ Lang::get('app.cancel') }}
					</a>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/rel-topik-mk/index.blade.php
@extends('layouts.master')

@section('content')
<div class="ui card fluid">
	<div class="content">
		<div class="ui breadcrumb">
			<div class="section">{{ Lang::get('app.home') }}</div>
			<i class="right angle icon divider"></i>
			<div class="active section">{{ Lang::get('app.rel_topik_mk') }}</div>
		</div>
	</div>
</div>
<div class="ui card fluid">
	<div class="extra content">
		<div class="ui grid">
			<div class="three wide column">
				<a href="{{ route('rel-topik-mk.create')}}" class="ui small green button">
					<i class="plus square icon"></i> {{ Lang::get('app.add') }}
				</a>
			</div>
			<div class="thirteen wide column">
				<!-- Messages -->
				@php $messages = session('messages'); @endphp
				@if($messages)
				@if(is_array($messages))
				<div class="ui small @if(session('status') == 1) positive @else negative @endif message" role="alert">
					<ul>
						@foreach($messages as $message)
						<li>{{ $message }}</li>
						@endforeach
					</ul>
				</div>
				@else
				<div class="ui small @if(session('status') == 1) positive @else negative @endif message" role="alert">
					{{ session('messages') }}
				</div>
				@endif
				@endif
			</div>
		</div>
	</div>
	<div class="content">
		<div class="description">
			<table class="ui celled red table responsive" cellspacing="0" width="100%" id="thegrid">
				<thead>
					<tr>
						<th>{{ Lang::get('app.id') }}</th>
						<th>{{ Lang::get('app.topik') }}</th>
						<th>{{ Lang::get('app.mata_kuliah') }}</th>
						<th style="width:50px"></th>
					</tr>
				</thead>
				<tbody></tbody>
			</table>
		</div>
	</div>
</div>
@endsection
@section('scripts')
<script type="text/javascript">
	var theGrid = null;
	$(document).ready(function(){
		theGrid = $('#thegrid').DataTable({
			'info'      : false,
			'drawCallback': function (settings) { 
				$(".dataTables_filter").each(function () { 
					$(this).find("label").addClass('ui input field'); 
				}); 
			},
			'ordering'  : true,
			'processing': true,
			'responsive': true,
			'serverSide': true,
			'ajax'      : {
				url: "{{ route('rel-topik-mk.index')}}/grid",
				dataSrc: function(result){
					console.log(result);
					return result.data;
				}
			},
			columns: [
			{ data: 'id', name: 'id', searchable: false , width: '20px'},
			{ data: 'nama', name: 'nama' },
			{ data: 'kuliah', name: 'kuliah' },
			{ data: 'buttons', name: 'buttons', orderable: false, searchable: false },
			],
			'language'  : {
				'emptyTable'    : Lang.datatable.no_data,
				'infoEmpty'     : Lang.datatable.no_data,
				'zeroRecords'   : Lang.datatable.no_data,
				'thousands'     : ',',
				'lengthMenu'    : Lang.datatable.showing_n_data,
				'loadingRecords': Lang.datatable.loading_data,
				'processing'    : Lang.datatable.processing_data,
				'search'        : "",
				'searchPlaceholder' : Lang.app.search,
				'paginate': {
					'first'     : '<<',
					'last'      : '>>',
					'next'      : '>',
					'previous'  : '<'
				}
			}
		});
	});

	function doDelete(id) {
		if(confirm('Apakah anda yakin ingin menghapus data ini?')) {
			$.ajax({ url: '{{ route('rel-topik-mk.index') }}/' + id, type: 'DELETE'}).done(function() {
				theGrid.ajax.reload();
			});
		}
		return false;
	}
</script>
@endsection

resources/views/rel-topik-mk/show.blade.php
@extends('layouts.master')

@section('content')
<div class="ui card fluid">
	<div class="content">
		<div class="ui breadcrumb">
			<div class="section">{{ Lang::get('app.home') }}</div>
			<i class="right angle icon divider"></i>
			<a href="{{ route('rel-topik-mk.index') }}" class="section">{{ Lang::get('app.rel_topik_mk') }}</a>
			<i class="right angle icon divider"></i>
			<div class="section">{{ $model->topik->nama }} - {{ $model->mk->nama }}</div>
			<i class="right angle icon divider"></i>
			<div class="active section">{{ Lang::get('app.detail') }}</div>
		</div>
	</div>
</div>
<div class="ui card fluid">
	<div class="content">
		<div class="description">
			<table class="ui celled table">
				<tbody>
					<tr>
						<td class="collapsing active">{{ Lang::get('app.id') }}</td>
						<td>{{ $model->id }}</td>
					</tr>
					<tr>
						<td class="collapsing active">{{ Lang::get('app.topik') }}</td>
						<td>{{ $model->topik->nama }}</td>
					</tr>
					<tr>
						<td class="collapsing active">{{ Lang::get('app.mata_kuliah') }}</td>
						<td>{{ $model->mk->nama }}</td>
					</tr>
				</tbody>
			</table>
			<!-- Buttons -->
			<div class="ui small buttons">
				<a class="ui yellow button" href="{{ route('rel-topik-mk.edit', $model->id) }}">
					<i class="edit icon"></i> {{ Lang::get('app.edit') }}
				</a>
				<a class="ui button" href="{{ route('rel-topik-mk.index') }}">
					<i class="hand point left outline icon"></i> {{ Lang::get('app.back') }}
				</a>
			</div>
		</div>
	</div>
</div>
@endsection