routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();


Route::get('/bahan-kajian/grid', 'BahanKajianController@grid');
Route::resource('/bahan-kajian', 'BahanKajianController');
Route::get('/blooms-taxonomy/grid', 'BloomsTaxonomyController@grid');
Route::resource('/blooms-taxonomy', 'BloomsTaxonomyController');
Route::get('/cpl/grid', 'CplController@grid');
Route::resource('/cpl', 'CplController');
Route::get('/mata-kuliah/grid', 'MataKuliahController@grid');
Route::resource('/mata-kuliah', 'MataKuliahController');
Route::get('/okupasi/grid', 'OkupasiController@grid');
Route::resource('/okupasi', 'OkupasiController');
Route::get('/permission-role/grid', 'PermissionRoleController@grid');
Route::resource('/permission-role', 'PermissionRoleController');
Route::get('/permission/grid', 'PermissionController@grid');
Route::resource('/permission', 'PermissionController');
Route::get('/prodi/grid', 'ProdiController@grid');
Route::resource('/prodi', 'ProdiController');
Route::get('/profil-lulusan/grid', 'ProfilLulusanController@grid');
Route::resource('/profil-lulusan', 'ProfilLulusanController');
Route::get('/ranah-topik/grid', 'RanahTopikController@grid');
Route::resource('/ranah-topik', 'RanahTopikController');
Route::get('/rel-cpl-bk/grid', 'RelCplBkController@grid');
Route::resource('/rel-cpl-bk', 'RelCplBkController');
Route::get('/rel-topik-bk/grid', 'RelTopikBkController@grid');
Route::resource('/rel-topik-bk', 'RelTopikBkController');
Route::get('/rel-topik-mk/grid', 'RelTopikMkController@grid');
Route::resource('/rel-topik-mk', 'RelTopikMkController');
Route::get('/role/grid', 'RoleController@grid');
Route::resource('/role', 'RoleController');
Route::get('/user-prodi/grid', 'UserProdiController@grid');
Route::resource('/user-prodi', 'UserProdiController');
Route::get('/user-role/grid', 'RoleUserController@grid');
Route::resource('/user-role', 'RoleUserController');
Route::get('/users/grid', 'UserController@grid');
Route::resource('/users', 'UserController');

app/Role.php
<?php 

namespace App;

use Zizaco\Entrust\EntrustRole;

class Role extends EntrustRole
{

}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Role;

use DB;

class RoleController extends Controller
{
    //
    public function __construct()
    {
        //$this->middleware('auth');
    }


    public function index(Request $request)
	{
	    return view('role.index', []);
	}

	public function create(Request $request)
	{
	    return view('role.add', [
	        []
	    ]);
	}

	public function edit(Request $request, $id)
	{
		$role = Role::findOrFail($id);
	    return view('role.add', [
	        'model' => $role	    ]);
	}

	public function show(Request $request, $id)
	{
		$role = Role::findOrFail($id);
	    return view('role.show', [
	        'model' => $role	    ]);
	}

	public function grid(Request $request)
	{
		$len = $_GET['length'];
		$start = $_GET['start'];

		$select = "SELECT *,1,2 ";
		$presql = " FROM roles a ";
		if($_GET['search']['value']) {	
			$presql .= " WHERE name LIKE '%".$_GET['search']['value']."%' or display_name LIKE '%".$_GET['search']['value']."%' or id LIKE '%".$_GET['search']['value']."%' or description LIKE '%".$_GET['search']['value']."%' ";
		}
		
		$presql .= "  ";

		$sql = $select.$presql." LIMIT ".$start.",".$len;


		$qcount = DB::select("SELECT COUNT(a.id) c".$presql);
		//print_r($qcount);
		$count = $qcount[0]->c;

		$results = DB::select($sql);
		$ret = [];
		foreach ($results as $row) {
			$r = [];
			foreach ($row as $value) {
				$r[] = $value;
			}
			$ret[] = $r;
		}

		$ret['data'] = $ret;
		$ret['recordsTotal'] = $count;
		$ret['iTotalDisplayRecords'] = $count;

		$ret['recordsFiltered'] = count($ret);
		$ret['draw'] = $_GET['draw'];

		echo json_encode($ret);

	}


	public function update(Request $request) {
	    //
	    /*$this->validate($request, [
	        'name' => 'required|max:255',
	    ]);*/
		$role = null;
		if($request->id > 0) { $role = Role::findOrFail($request->id); }
		else { 
			$role = new Role;
		}
	    

	    		
			    $role->id = $request->id?:0;
				
	    		
					    $role->name = $request->name;
		
	    		
					    $role->display_name = $request->display_name;
		
	    		
					    $role->description = $request->description;
		
	    	    //$role->user_id = $request->user()->id;
	    $role->save();

	    return redirect()->route('role.index');

	}

	public function store(Request $request)
	{
		return $this->update($request);
	}

	public function destroy(Request $request, $id) {
		
		$role = Role::findOrFail($id);

		$role->delete();
		return "OK";
	    
	}

	
}

resources/views/role/add.blade.php
@extends('layouts.master')

@section('content')

<div class="ui card fluid">
  <div class="content">
    <a class="header">Role</a>
    <div class="meta">
      <span>@if(isset($model)) Modify @else Add @endif Role</span>
    </div>
    <div class="description">
        <form action="{{ route('role.index')}}{{( isset($model) ? "/" . $model->id : "") }}" method="POST" class="ui form">
            {{ csrf_field() }}

            @if (isset($model))
                <input type="hidden" name="_method" value="PATCH">
            @endif


            <input type="hidden" name="id" id="id" value="{{$model['id'] or ''}}" readonly="readonly">
            <div class="field">
                <label>Name</label>
                <input type="text" name="name" id="name" value="{{$model['name'] or ''}}">
            </div>
            <div class="field">
                <label>Display Name</label>
                <input type="text" name="display_name" id="display_name" value="{{$model['display_name'] or ''}}">
            </div>
            <div class="field">
                <label>Description</label>
                <input type="text" name="description" id="description" value="{{$model['description'] or ''}}">
            </div>
                                    
            <button type="submit" class="ui primary button"><i class="plus square icon"></i> Save</button>
            <a class="ui red button" href="{{ route('role.index') }}"><i class="hand point left outline icon"></i> Back</a>
        </form>
    </div>
  </div>
</div>
@endsection

resources/views/role/index.blade.php
@extends('layouts.master')

@section('content')
<div class="ui card fluid">
  <div class="content">
    <a class="header">Role</a>
    <div class="meta">
      <span>List of Role</span>
    </div>
    <div class="description">
		<table class="ui celled table" cellspacing="0" width="100%" id="thegrid">
		  <thead>
		    <tr>
		        <th>ID</th>
		        <th>Name</th>
		        <th>Display Name</th>
		        <th>Description</th>
		        <th style="width:50px"></th>
		        <th style="width:50px"></th>
		    </tr>
		  </thead>
		  <tbody>
		  </tbody>
		</table>
    </div>
  </div>
  <div class="extra content">
    <a href="{{ route('role.create') }}" class="ui primary button">Add</a>
  </div>
</div>
@endsection
@section('scripts')
    <script type="text/javascript">
        var theGrid = null;
        $(document).ready(function(){
            theGrid = $('#thegrid').DataTable({
                "processing": true,
                "serverSide": true,
                "ordering": true,
                "responsive": true,
                "ajax": "{{ route('role.index') }}/grid",
                "columnDefs": [
                    {
                        "render": function ( data, type, row ) {
                            return '<a href="{{ route('role.index') }}/'+row[0]+'">'+data+'</a>';
                        },
                        "targets": 1
                    },
                    {
                        "render": function ( data, type, row ) {
                            return '<a href="{{ route('role.index') }}/'+row[0]+'/edit" class="ui green button">Update</a>';
                        },
                        "targets": 4                    },
                    {
                        "render": function ( data, type, row ) {
                            return '<a href="#" onclick="return doDelete('+row[0]+')" class="ui red button">Delete</a>';
                        },
                        "targets": 4+1
                    },
                ]
            });
        });
        function doDelete(id) {
            if(confirm('You really want to delete this record?')) {
               $.ajax({ url: '{{ route('role.index') }}/' + id, type: 'DELETE'}).done(function() {
                theGrid.ajax.reload();
               });
            }
            return false;
        }
    </script>
@endsection

resources/views/role/show.blade.php
@extends('layouts.master')

@section('content')

<div class="ui card fluid">
  <div class="content">
    <a class="header">Role</a>
    <div class="meta">
      <span>View Role</span>
    </div>
    <div class="description">
        <form action="{{ route('role.index') }}" method="POST" class="ui form">


                
        <div class="field">
            <label>ID</label>
            <input type="text" name="id" id="id" value="{{$model['id'] or ''}}" readonly="readonly">
        </div>
        
                
        <div class="field">
            <label>Name</label>
            <input type="text" name="name" id="name" value="{{$model['name'] or ''}}" readonly="readonly">
        </div>
        
                
        <div class="field">
            <label>Display Name</label>
            <input type="text" name="display_name" id="display_name" value="{{$model['display_name'] or ''}}" readonly="readonly">
        </div>
        
        
        <a class="ui red button" href="{{ route('role.index') }}"><i class="hand point left outline icon"></i> Back</a>


        </form>
    </div>
  </div>
</div>
@endsection