routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();


Route::get('/bahan-kajian/grid', 'BahanKajianController@grid');
Route::resource('/bahan-kajian', 'BahanKajianController');
Route::get('/blooms-taxonomy/grid', 'BloomsTaxonomyController@grid');
Route::resource('/blooms-taxonomy', 'BloomsTaxonomyController');
Route::get('/cpl/grid', 'CplController@grid');
Route::resource('/cpl', 'CplController');
Route::get('/mata-kuliah/grid', 'MataKuliahController@grid');
Route::resource('/mata-kuliah', 'MataKuliahController');
Route::get('/okupasi/grid', 'OkupasiController@grid');
Route::resource('/okupasi', 'OkupasiController');
Route::get('/permission-role/grid', 'PermissionRoleController@grid');
Route::resource('/permission-role', 'PermissionRoleController');
Route::get('/permission/grid', 'PermissionController@grid');
Route::resource('/permission', 'PermissionController');
Route::get('/prodi/grid', 'ProdiController@grid');
Route::resource('/prodi', 'ProdiController');
Route::get('/profil-lulusan/grid', 'ProfilLulusanController@grid');
Route::resource('/profil-lulusan', 'ProfilLulusanController');
Route::get('/ranah-topik/grid', 'RanahTopikController@grid');
Route::resource('/ranah-topik', 'RanahTopikController');
Route::get('/rel-cpl-bk/grid', 'RelCplBkController@grid');
Route::resource('/rel-cpl-bk', 'RelCplBkController');
Route::get('/rel-topik-bk/grid', 'RelTopikBkController@grid');
Route::resource('/rel-topik-bk', 'RelTopikBkController');
Route::get('/rel-topik-mk/grid', 'RelTopikMkController@grid');
Route::resource('/rel-topik-mk', 'RelTopikMkController');
Route::get('/role/grid', 'RoleController@grid');
Route::resource('/role', 'RoleController');
Route::get('/user-prodi/grid', 'UserProdiController@grid');
Route::resource('/user-prodi', 'UserProdiController');
Route::get('/user-role/grid', 'RoleUserController@grid');
Route::resource('/user-role', 'RoleUserController');
Route::get('/users/grid', 'UserController@grid');
Route::resource('/users', 'UserController');

app/RoleUser.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class RoleUser extends Model
{
    //
    protected $table = 'role_user';
    public $timestamps = false;

}

app/Http/Controllers/RoleUserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\RoleUser;
use App\Role;
use App\User;

use DB;

class RoleUserController extends Controller
{
    //
    public function __construct()
    {
        //$this->middleware('auth');
    }


    public function index(Request $request)
	{
	    return view('role-user.index', []);
	}

	public function create(Request $request)
	{
		$role = User::select('users.id','users.email')
		->leftJoin('role_user', 'users.id', '=', 'role_user.user_id')
		->leftJoin('roles', 'users.id', '=', 'role_user.user_id')
		->where('role_user.user_id',null)
		->get();
		// dd($role);
		$roles = Role::select('id','display_name')->get();
	    return view('role-user.add', ['role'=>$role,'roles'=>$roles]);
	}

	public function edit(Request $request, $id)
	{	
		$role_user = RoleUser::where('user_id',$id)->get();
		$role = User::select('users.id','users.email')
		->where('users.id',$id)
		->get();
		// dd($role);
		$roles = Role::select('id','display_name')->get();
	    return view('role-user.add', [
	        'model' => $role_user[0],'role'=>$role,'roles'=>$roles]);
	}

	public function show(Request $request, $id)
	{
		$role_user = RoleUser::where('user_id',$id)->get();
		$results = DB::select('select users.email, roles.display_name from role_user join users on users.id = role_user.user_id join roles on roles.id = role_user.role_id where role_user.user_id ='.$id);
		$model = ['user_id'=>$results[0]->email,'role_id'=>$results[0]->display_name];
	    return view('role-user.show', ['model' => $model]);
	}

	public function grid(Request $request)
	{
		$len = $_GET['length'];
		$start = $_GET['start'];

		$select = "SELECT a.user_id, a.role_id, b.display_name, c.email,1,2 ";
		$presql = " FROM role_user a join roles b on a.role_id = b.id join users c on c.id = a.user_id";
		if($_GET['search']['value']) {	
			$presql .= " WHERE b.display_name LIKE '%".$_GET['search']['value']."%' or c.email LIKE '%".$_GET['search']['value']."%' ";
		}
		
		$presql .= "  ";

		$sql = $select.$presql." LIMIT ".$start.",".$len;


		$qcount = DB::select("SELECT COUNT(a.user_id) c".$presql);
		//print_r($qcount);
		$count = $qcount[0]->c;

		$results = DB::select($sql);
		$ret = [];
		foreach ($results as $row) {
			$r = [];
			foreach ($row as $value) {
				$r[] = $value;
			}
			$ret[] = $r;
		}

		$ret['data'] = $ret;
		$ret['recordsTotal'] = $count;
		$ret['iTotalDisplayRecords'] = $count;

		$ret['recordsFiltered'] = count($ret);
		$ret['draw'] = $_GET['draw'];

		echo json_encode($ret);

	}


	public function update(Request $request) {
	    //
	    /*$this->validate($request, [
	        'name' => 'required|max:255',
	    ]);*/

	    // dd($request);
	 	DB::table('role_user')
        ->where('user_id', $request->user_id)
        ->update(['role_id' => $request->role_id]);

	    return redirect()->route('user-role.index');

	}

	public function store(Request $request)
	{
		DB::table('role_user')->insert(
		    ['user_id' => $request->user_id, 'role_id' => $request->role_id, ]
		);
		
	    return redirect()->route('user-role.index');
		// return $this->update($request);
	}

	public function destroy(Request $request, $id) {
		
		// $role_user = RoleUser::where('user_id',$id)->get();

		// dd($role_user);
		DB::table('role_user')->where('user_id', '=', $id)->delete();
		return "OK";
	    
	}

	
}

resources/views/role-user/add.blade.php
@extends('layouts.master')

@section('content')

<div class="ui card fluid">
  <div class="content">
    <a class="header">User Role</a>
    <div class="meta">
      <span>@if(isset($model)) Modify @else Add @endif User Role</span>
    </div>
    <div class="description">
        <form action="{{ route('user-role.index')}}{{( isset($model) ? "/" . $model->id : "") }}" method="POST" class="ui form">
            {{ csrf_field() }}

            @if (isset($model))
                <input type="hidden" name="_method" value="PATCH">
            @endif


            <div class="field">
                <label>User</label>
                @if(count($role)==0)
                <input type="text" id="user_id" value="Tidak ada user tersedia" readonly="readonly">
                @else
                <input type="hidden" name="user_id" id="user_id" value="{{ (isset($model)? $model['user_id']:'') }}" readonly="readonly">
                <select class="ui search dropdown" name="user_id" id="user_id" {{ (isset($model)?'disabled="disabled"':'') }}>
                    <option value="">User</option>
                @foreach($role as $val)
                  <option value="{{ $val->id }}" {{ (isset($model)?(($model['user_id']==$val->id)?'selected':''):'') }}>{{ $val->email }}</option>
                @endforeach
                </select>
                @endif
            </div>
            <div class="field">
                <label>Role</label>
                @if(count($roles)==0)
                <input type="text" id="role_id" value="Tidak ada role tersedia" readonly="readonly">
                @else
                <select class="ui search dropdown" name="role_id" id="role_id">
                    <option value="">Role</option>
                @foreach($roles as $val)
                  <option value="{{ $val->id }}" {{ (isset($model)?(($model['role_id']==$val->id)?'selected':''):'') }}>{{ $val->display_name }}</option>
                @endforeach
                </select>
                @endif
            </div>
                                                            
            <button type="submit" class="ui primary button"><i class="plus square icon"></i> Save</button>
            <a class="ui red button" href="{{ route('user-role.index') }}"><i class="hand point left outline icon"></i> Back</a>
        </form>
    </div>
  </div>
</div>
@endsection

@section('scripts')
<script type="text/javascript">
    $(document).ready(function() {
        $('select.dropdown')
          .dropdown()
        ;
    });
</script>
@endsection

resources/views/role-user/index.blade.php
@extends('layouts.master')

@section('content')
<div class="ui card fluid">
  <div class="content">
    <a class="header">User Role</a>
    <div class="meta">
      <span>List of User Role</span>
    </div>
    <div class="description">
		<table class="ui celled table" cellspacing="0" width="100%" id="thegrid">
		  <thead>
		    <tr>
		        		        <th>User</th>
		        		        <th>Role</th>
		        		        <th style="width:50px"></th>
		        <th style="width:50px"></th>
		    </tr>
		  </thead>
		  <tbody>
		  </tbody>
		</table>
    </div>
  </div>
  <div class="extra content">
    <a href="{{route('user-role.create')}}" class="ui primary button">Add</a>
  </div>
</div>
@endsection
@section('scripts')
    <script type="text/javascript">
        var theGrid = null;
        $(document).ready(function(){
            theGrid = $('#thegrid').DataTable({
                "processing": true,
                "serverSide": true,
                "ordering": true,
                "responsive": true,
                "ajax": "{{route('user-role.index')}}/grid",
                "columnDefs": [
                    {
                        "render": function ( data, type, row ) {
                            return row[3];
                        },
                        "targets": 0
                    },
                    {
                        "render": function ( data, type, row ) {
                            return '<a href="{{ route('user-role.index') }}/'+row[0]+'">'+row[2]+'</a>';
                        },
                        "targets": 1
                    },
                    {
                        "render": function ( data, type, row ) {
                            return '<a href="{{ route('user-role.index') }}/'+row[0]+'/edit" class="ui green button">Update</a>';
                        },
                        "targets": 2
                    },
                    {
                        "render": function ( data, type, row ) {
                            return '<a href="#" onclick="return doDelete('+row[0]+')" class="ui red button">Delete</a>';
                        },
                        "targets": 2+1
                    },
                ]
            });
        });
        function doDelete(id) {
            if(confirm('You really want to delete this record?')) {
               $.ajax({ url: '{{ route('user-role.index') }}/' + id, type: 'DELETE'}).done(function() {
                theGrid.ajax.reload();
               });
            }
            return false;
        }
    </script>
@endsection

resources/views/role-user/show.blade.php
@extends('layouts.master')

@section('content')

<div class="ui card fluid">
  <div class="content">
    <a class="header">User Role</a>
    <div class="meta">
      <span>View User Role</span>
    </div>
    <div class="description">
        <form action="{{ route('user-role.index') }}" method="POST" class="ui form">


                
        <div class="field">
            <label>User</label>
            <input type="text" name="user_id" id="user_id" value="{{$model['user_id'] or ''}}" readonly="readonly">
        </div>
        
                
        <div class="field">
            <label>Role</label>
            <input type="text" name="role_id" id="role_id" value="{{$model['role_id'] or ''}}" readonly="readonly">
        </div>
        
        
        <a class="ui red button" href="{{ route('user-role.index') }}"><i class="hand point left outline icon"></i> Back</a>


        </form>
    </div>
  </div>
</div>
@endsection